# Generated by Django 6.0.5 on 2026-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('forum', 'Forum'), ('meeting', 'Meeting'), ('youth_program', 'Youth Program')], default='forum', max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=300)),
                ('venue', models.CharField(blank=True, max_length=250)),
                ('event_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
