# Generated by Django 6.0.5 on 2026-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nuba Elite Forum', max_length=100)),
                ('tagline', models.CharField(default='Uniting Voices. Empowering Communities.', max_length=300)),
                ('about_text', models.TextField()),
                ('mission_statement', models.TextField()),
                ('vision_statement', models.TextField()),
                ('contact_email', models.EmailField(default='info@nubaforum.org', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
