# Generated by Django 6.0.5 on 2026-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chair', 'Vice Chairperson'), ('secretary', 'Secretary General'), ('treasurer', 'Treasurer'), ('coordinator', 'Program Coordinator'), ('advisor', 'Advisor'), ('board', 'Board Member')], max_length=20)),
                ('bio', models.TextField()),
                ('expertise', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('profile_image', models.ImageField(upload_to='leadership/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leadership Member',
                'verbose_name_plural': 'Leadership Members',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
