# Generated by Django 6.0.5 on 2026-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('membership_type', models.CharField(choices=[('individual', 'Individual'), ('student', 'Student'), ('professional', 'Professional'), ('organization', 'Organization')], default='individual', max_length=20)),
                ('interest_areas', models.CharField(help_text='Comma-separated interests', max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('motivation', models.TextField(help_text='Why do you want to join NEF?')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('is_approved', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
